
@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}
@contentType = application/json

@Authorization_Token =  Bearer {{token}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiaWJyYSIsImlzT3duZXIiOnRydWUsInJvbGUiOiJTdXBlciBhZG1pbiIsImlzQWN0aXZhdGVkIjp0cnVlLCJpc1JlcXVlc3RWaXNpYmxlIjp0cnVlLCJpc0tleXNWaXNpYmxlIjp0cnVlLCJpc0tleXNFZGl0YWJsZSI6dHJ1ZSwiaXNIaXN0b3JpY1Zpc2libGUiOnRydWUsImlhdCI6MTU3OTM2NTQ0NiwiZXhwIjoxNTc5OTcwMjQ2fQ.IbqOVQEsjD_iJXTMm_RT5cfHHmT30jJKs03bBPHxujE

@connectedUser = ibra




###

// GET ALL
GET /api/v1/partner HTTP/1.1
Host: {{host}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}


###


// GET a specefic partner profile
GET /api/v1/partner/profile/12340 HTTP/1.1
Host: {{host}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}


###


// Change a specific partner profile infos
PUT /api/v1/partner/profile/12341/update HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}

{
	"tradeRegister": "12341",
	"name":"Company name 1",
	"category" : "vtc",
	"isActive" : true
}



###


// Create Partner
POST /api/v1/partner/ HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}

{
	"tradeRegister": "12340",
	"name":"Company name 0",
	"category" : "vtc",
	"isActive" : true
}






