

@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}
@contentType = application/json

@identificator = cibra

@Authorization_Token =  Bearer {{token}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiY2xpZW50NSIsImlzT3duZXIiOmZhbHNlLCJyb2xlIjoiQmFzaWMiLCJpc0FjdGl2YXRlZCI6dHJ1ZSwiaXNSZXF1ZXN0VmlzaWJsZSI6dHJ1ZSwiaXNLZXlzVmlzaWJsZSI6dHJ1ZSwiaXNLZXlzRWRpdGFibGUiOnRydWUsImlzSGlzdG9yaWNWaXNpYmxlIjp0cnVlLCJpYXQiOjE1NzkzODQxMjYsImV4cCI6MTU3OTk4ODkyNn0.dTYiOfGm8Lef8bhnc5V3jo0UhnSTAemZSnMvXg2KG6g

@connectedUser = client5


##

// Create User 
POST /api/v1/client/ HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}

{
	"identificator": "client5",
	"role":"Basic",
	"password" : "pass",
	"confirmPassword" : "pass",
    "designation": "Not Unic name",
	"isActivated" : true,
	"isRequestVisible" : true,
	"isKeysVisible" : true,
	"isKeysEditable" : true,
	"isHistoricVisible" : true,
	"tradeRegister" : "12341"
}

### 

// get user profile
GET /api/v1/client/profile/{{identificator}} HTTP/1.1
Host: {{host}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}


###

// get all Clients
GET /api/v1/client/ HTTP/1.1
Host: {{host}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}


###

GET /api/v1/client/12341/accounts HTTP/1.1
Host: {{host}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}


###

// Update user Basic infos

PUT /api/v1/client/profile/{{identificator}} HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}
Authorization: {{Authorization_Token}}
identificator: {{connectedUser}}

{
	"role" : "Super admin",
    "designation": "Not Unic name",
	"isActivated" : true,
	"isRequestVisible" : true,
	"isKeysVisible" : false,
	"isKeysEditable" : true,
	"isHistoricVisible" : true
}