

@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiaWJyYSIsImlzT3duZXIiOnRydWUsInJvbGUiOiJTdXBlciBhZG1pbiIsImlzQWN0aXZhdGVkIjp0cnVlLCJpc1JlcXVlc3RWaXNpYmxlIjp0cnVlLCJpc0tleXNWaXNpYmxlIjp0cnVlLCJpc0tleXNFZGl0YWJsZSI6dHJ1ZSwiaXNIaXN0b3JpY1Zpc2libGUiOnRydWUsImlhdCI6MTU3ODc4NDUwOSwiZXhwIjoxNTc5Mzg5MzA5fQ.FIh5vH66T4jbdNijQ0ugTvuxtZI-Z5yaAk_ce_pidAQ

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiaWJyYSIsImlzT3duZXIiOnRydWUsInJvbGUiOiJTdXBlciBhZG1pbiIsImlhdCI6MTU3ODc4NDUwOX0.Us0oGhEKr7BZxpZ43X9xd6CYgvOJfantKy5NQ2MAPRY

##

// Login get the Access and Refresh token
GET  /dashboard/api/v1/auth/login HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
	"identificator" : "cibra1",
	"password" : "pass"
}


###


GET  /dashboard/api/v1/auth/refresh HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
	"identificator": "ibra" ,
	"token" : "eyJhbGcieyJ1c2VybmFtZyI",
	"refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiaWJyYSIsImlzT3duZXIiOnRydWUsInJvbGUiOiJTdXBlciBhZG1pbiIsImlhdCI6MTU3ODc4NjE1Nn0.CglfsAPBIaqXNuKnoJO4d35__XB66WESKPQield6BT4"
}
